title: Dhaliwal Solutions
baseURL: /
params:
  footer:
    content: '&copy; All rights reserved.'
    links: []
  header:
    bg: dark
    has_nav: true
    has_social: true
    profile_img: images/avatar.png
    tagline: Softwares and Websites
    title: Dhaliwal Solutions
  layout_style: overflow
  palette: blue
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
